"""
Post-processing output validation for parking chatbot responses.

Provides a keyword-based guardrail that verifies LLM-generated responses
remain on-topic (parking-related) and do not contain forbidden content
patterns. This acts as a final safety net before a response is returned
to the user, catching cases where the LLM drifts off-topic despite
upstream intent classification and prompt constraints.

Validation is intentionally lightweight (string matching) to add minimal
latency. It complements - but does not replace - the upstream intent
classifier and system prompt restrictions.
"""

import logging
from typing import Any, Dict

logger = logging.getLogger(__name__)


class OutputValidator:
    """Post-processing validation that ensures responses are parking-related.

    Applies a two-stage keyword filter to every outgoing response:

    1. **Blacklist check** -- scans for forbidden patterns (creative writing,
       math, finance, etc.). If any are found the response is rejected.
    2. **Whitelist check** -- verifies the response contains at least one
       parking-related keyword. If none are found the response is rejected.

    Rejected responses are replaced with a standard off-topic message that
    redirects the user to parking queries.

    Usage::

        validator = OutputValidator()
        result = validator.validate("Downtown Plaza has 45 available spaces.")
        # result == {
        #     "is_valid": True,
        #     "response": "Downtown Plaza has 45 available spaces.",
        #     "reason": ""
        # }

    Attributes:
        PARKING_KEYWORDS: Set of lowercase tokens that indicate a response
            is parking-related.  At least one must appear for validation
            to pass.
        FORBIDDEN_PATTERNS: Set of lowercase tokens whose presence
            automatically causes rejection.
        OFF_TOPIC_MESSAGE: Canned reply returned when a response fails
            validation.
    """

    # Whitelist: response must contain at least one of these tokens
    PARKING_KEYWORDS: set[str] = {
        "parking", "park", "space", "spot", "lot", "garage",
        "availability", "available", "occupied", "reserved",
        "price", "pricing", "rate", "fee", "cost",
        "hour", "hours", "open", "close", "closed",
        "reservation", "reserve", "book", "booking",
        "downtown", "airport", "plaza", "facility",
    }

    # Blacklist: if any of these tokens appear the response is rejected
    FORBIDDEN_PATTERNS: set[str] = {
        "poem", "poetry", "verse", "rhyme",
        "joke", "funny", "humor",
        "story", "tale", "narrative",
        "recipe", "cook", "ingredient",
        "math", "calculate", "equation",
        "investment", "stock", "trade",
    }

    OFF_TOPIC_MESSAGE: str = (
        "I can only help with parking-related questions like availability, "
        "pricing, reservations, and operating hours. How can I help with your parking needs?"
    )

    def validate(self, response: str) -> Dict[str, Any]:
        """Validate that a chatbot response is on-topic and safe to return.

        Runs the response text through the blacklist and whitelist checks,
        in that order.  The first failing check short-circuits evaluation.

        Args:
            response: The raw text generated by the LLM.

        Returns:
            A dictionary with three keys:

            - **is_valid** (*bool*) -- ``True`` if the response passed both
              checks, ``False`` otherwise.
            - **response** (*str*) -- The original *response* when valid, or
              :pyattr:`OFF_TOPIC_MESSAGE` when rejected.
            - **reason** (*str*) -- Empty string when valid.  When rejected,
              a human-readable explanation of why (e.g. which forbidden
              pattern was found, or that no parking keyword was present).
        """
        response_lower = response.lower()
        response_words = set(response_lower.split())

        # --- Stage 1: blacklist (forbidden patterns) -----------------------
        found_forbidden = self.FORBIDDEN_PATTERNS & response_words
        if found_forbidden:
            # Sort for deterministic log output
            matched = ", ".join(sorted(found_forbidden))
            reason = f"Response contained forbidden pattern(s): {matched}"
            logger.warning(
                "Output rejected -- %s. Response preview: '%.120s'",
                reason,
                response,
            )
            return {
                "is_valid": False,
                "response": self.OFF_TOPIC_MESSAGE,
                "reason": reason,
            }

        # --- Stage 2: whitelist (parking keywords) -------------------------
        found_parking = self.PARKING_KEYWORDS & response_words
        if not found_parking:
            reason = "Response did not contain any parking-related keywords"
            logger.warning(
                "Output rejected -- %s. Response preview: '%.120s'",
                reason,
                response,
            )
            return {
                "is_valid": False,
                "response": self.OFF_TOPIC_MESSAGE,
                "reason": reason,
            }

        # --- Both checks passed --------------------------------------------
        return {
            "is_valid": True,
            "response": response,
            "reason": "",
        }
